services:
  web:
    build: .
    entrypoint: "bin/docker-entrypoint"
    command: "bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/var/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:development@db:5432
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: development

volumes:
  bundle:
  database:
